[package]
name = "ros_pointcloud2"
version = "0.1.0"
edition = "2021"
authors = ["Christopher Sieh <stelzo@steado.de>"]
description = "A library for working with pointcloud2 messages in Rust"
repository = "https://github.com/stelzo/ros_pointcloud2"
license = "MIT"
keywords = ["ros", "rosrust", "pointcloud2", "pointcloud", "message",]
categories = ["science::robotics", "encoding", "data-structures", "api-bindings"]
readme = "README.md"
documentation = "https://docs.rs/ros_pointcloud2"
homepage = "https://github.com/stelzo/ros_pointcloud2"
exclude = ["**/tests/**", "**/examples/**", "**/benches/**", "**/target/**", "**/build/**", "**/dist/**", "**/docs/**", "**/doc/**"]

[dependencies]
mem_macros = "1.0.1"
num-traits = "0.2.15"
rosrust_msg = "0.1.7"
fallible-iterator = "0.2.0"

